language: node_js

node_js:
    - "8.10"

services:
    - docker

install:
    - yarn install
    - docker-compose up -d

script:
    - yarn test

cache:
    yarn: true
    directories:
        - node_modules
