swagger: '2.0'

info:
  version: '1.0'
  title: Reminder API
  description: |
    Describes restful endpoints for the reminder api.
    ## Structure

    ### The Response
    Each successful response (`200` status code) follows same generic schema:
    ```json
    {
        'data': {
            ...
        }
    }
    ```

    On the other hand either client or server errors (`4xx-5xx`) follow this
    schema:
    ```json
    {
        'errors': [{
            ...
        }]
    }
    ```

    #### DATA
    The `data` key contains the information client requested.

    #### ERRORS
    The `errors` key contains `array` of request errors:
    ```json
    {
        "errors": [
            {
                "title": "something unexpected happened",
            }
        ]
    }
    ```

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
basePath: /v1
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Security                                   #
################################################################################
securityDefinitions:
  XApiKey:
      type: apiKey
      description: |
        The api key sent to client for the basic authentication
      name: x-api-key
      in: header

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /task:
    post:
      description: Creates a reminder task
      security:
        - XApiKey: []
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/CreateTask'
      responses:
        204:
          description: reminder task was created
        400:
          description: invalid payload
          schema:
            $ref: '#/definitions/ErrorResponse'
        401:
          description: not authenticated client
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: some server side error
          schema:
            type: object
            required:
              - error
            properties:
              error:
                $ref: '#/definitions/Error'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  CreateTask:
    type: object
    required:
      - url
      - method
      - remindMeAfter
    properties:
      url:
        type: string
      method:
        type: string
        enum:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
      remindMeAfter:
        type: number
        description: |
          Defines the number in seconds the reminder request should be sent.
          Valid values: an integer from 0 to 43,200 (12 hours).
      body:
        type: object
      headers:
        type: object
  ErrorResponse:
    type: object
    required:
      - errors
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
  Error:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: |
          A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of
          the problem, except for purposes of localization.
      source:
        $ref: '#/definitions/Source'
        description: An object containing references to the source of the error.
  Source:
    type: object
    properties:
      pointer:
        type: string
        description: |
          A JSON Pointer [RFC6901] to the associated entity in the request document
          [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].
      parameter:
        type: string
        description: A string indicating which URI query parameter caused the error.
