service: reminder

frameworkVersion: "^1.35.1"
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: ${self:custom.env.profile}
  stage: ${opt:stage, self:custom.env.stage}
  environment:
    ENVIRONMENT: ${self:provider.stage}
    SQS_URL: ${self:custom.env.sqs_url}
    SQS_REGION: ${self:custom.env.sqs_region}
    SQS_ACCESS_KEY_ID: ${self:custom.env.sqs_access_key_id}
    SQS_ACCESS_SECRET: ${self:custom.env.sqs_access_secret}
  apiKeys:
  - x-api-key

custom:
  env: ${file(${opt:environment})}

plugins:
  - serverless-offline

functions:
  health:
    handler: httpHandler.handle
    events:
     - http:
        path: health
        method: GET
        integration: lambda-proxy
  task:
    handler: httpHandler.handle
    events:
    - http:
        path: /v1/task
        method: POST
        integration: lambda-proxy
        private: true
